apiVersion: v2
name: fsm-akka-helm-umbrella-chart
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "${appVersion}"

dependencies:
  - name: customer-relationship-adapter-application
    version: "${customerRelationshipAdapterVersion}"
    repository: http://fsmakka.salgar.org/repository/fsm-akka-helm
    condition: customer-relation-adapter.enabled
