apiVersion: v2
name: fsm-akka-helm-umbrella-chart
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "${appVersion}"

dependencies:
  - name: address-check-application
    version: "${addressCheckVersion}"
    repository: oci://europe-west3-docker.pkg.dev/fsmakka/fsm-akka-helm-ar
    condition: address-check.enabled
  - name: credit-score-application
    version: "${creditScoreVersion}"
    repository: oci://europe-west3-docker.pkg.dev/fsmakka/fsm-akka-helm-ar
    condition: credit-score.enabled
  - name: customer-relationship-adapter-application
    version: "${customerRelationshipAdapterVersion}"
    repository: oci://europe-west3-docker.pkg.dev/fsmakka/fsm-akka-helm-ar
    condition: customer-relation-adapter.enabled
