name: Build with Java / Gradle CI for Integration Helm Publish
run-name: ${{ github.actor }}
on:
  workflow_call:
    inputs:
      umbrella-chart-version:
        required: true
        type: string
jobs:
  build:
    name: Building Helm Umbrella Chart for Service
    runs-on: ubuntu-latest
    env:
      HELM_USER: ${{ secrets.HELM_USER }}
      HELM_PASSWORD: ${{ secrets.HELM_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-name }}
          fetch-depth: 0
      - name: Display GitVersion output
        run: |
          echo "SemVer: $SEMVER"
      - name: Set up JDK17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_version: ${{ env.SEMVER }}
          ORG_GRADLE_PROJECT_HELM_USER: ${{ env.HELM_USER }}
          ORG_GRADLE_PROJECT_HELM_PASSWORD: ${{ env.HELM_PASSWORD }}
        with:
          arguments: |
            --version 
            --no-daemon
            -Pversion=${{ inputs.umbrella-chart-version }}
      - name: Helm Publish
        id: helmPublish
        run: |
          echo 'gradle -Pversion=${{ inputs.umbrella-chart-version }} Helm Publish'
      - name: Check Failure
        if: steps.helmPublish.outcome != 'success'
        run: exit 1
