name: Build with Java / Gradle CI and prepare Feature Environment
run-name: ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      branch-name:
        type: string
      source-repo:
        type: string
      version-number:
        type: string
jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Display Branch
        run: |
          echo "Branch: ${{ github.ref }}"
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-name }}
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
          additionalArguments: '"/b" "${{ inputs.branch-name }}"'
      - name: Display GitVersion ouput
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
  build:
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}
      HELM_USER: ${{ secrets.HELM_USER }}
      HELM_PASSWORD: ${{ secrets.HELM_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-name }}
          fetch-depth: 0
      - name: Display GitVersion output
        run: |
          echo "SemVer: $SEMVER"
      - name: Set up JDK17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle
      - name: Helm Publish
        run: |
          echo 'gradle -Pversion=${{ env.SEMVER }} -P${{ inputs.source-repo }}-version=${{ inputs.version-number }} Helm Publish'
  prepare-dev-environment:
    runs-on: ubuntu-latest
    needs:
      - calculate-version
      - build
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}
    steps:
      - name: Create Pull Request Branch for dev-environment
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: 'create-branch.yaml'
          repo: 'mehmetsalgar/fsm-akka-dev-environment'
          ref: 'development'
          token: ${{ secrets.PERSONAL_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 5m
          inputs: '{"branch-name": "${{ inputs.branch-name }}"}'
      - name: Prepare Pull Request Environment
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: 'prepare-services-pull-request.yaml'
          repo: 'mehmetsalgar/fsm-akka-dev-environment'
          ref: '${{ inputs.branch-name }}'
          token: ${{ secrets.PERSONAL_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 10m
          inputs: '{"source-repo": "address-check", "version": "${{ env.SEMVER }}"}'
