name: Cleanup after Branch Delete
run-name: Cleanup after Branch ${{ github.event.ref }} delete triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  delete:
jobs:
  call-cleanup-workflow:
    if: ${{ contains(github.event.ref, 'integration/') }}
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/cleanup-environment.yaml@master
    with:
      branch-name: "${{ github.event.ref }}"
    secrets: inherit