name: Build Pull Request Environment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Helm Umbrella Chart
        uses: mehmetsalgar/build.yaml
      - name: Prepare Environment
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: 'prepare-environment.yaml'
          repo: 'mehmetsalgar/fsm-akka-dev-environment'
          ref: 'bitnami'
          token: ${{ secrets.PERSONAL_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 5m
          inputs: '{"source-repo": "address-check", "version": "${{ env.SEMVER }}"}'
      - name: Prepare Services
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: 'prepare-environment.yaml'
          repo: 'mehmetsalgar/fsm-akka-dev-environment'
          ref: 'bitnami'
          token: ${{ secrets.PERSONAL_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 5m
          inputs: '{"source-repo": "address-check", "version": "${{ env.SEMVER }}"}'
