name: Continuous Deployment Integration
run-name: ${{ github.actor }}
on:
  push:
    branches: [integration/**]
jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Display Branch
        run: |
          echo "Branch: ${{ github.ref }}"
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-name }}
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
          additionalArguments: '"/b" "${{ inputs.branch-name }}"'
      - name: Display GitVersion ouput
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
  build:
    needs: calculate-version
    uses: mehmetsalgar/fsm-akka-helm-umbrella-chart/.github/workflows/build-for-integration.yaml@integration/1.2
    with:
      source-repo: ${{ inputs.branch-name }}
      umbrella-chart-version: ${{ needs.calculate-version.outputs.semVer }}
      version-number: ${{ inputs.version-number }}
    security: inherit
  prepare-dev-environment:
    name: Building Integration Environment for Kubernetes
    needs:
      - build
    uses: mehmetsalgar/fsm-akka-helm-umbrella-chart/.github/workflows/build-for-service.yaml@integration/1.2
    with:
      branch-name: ${{ inputs.branch-name }}
      tag: ${{ needs.calculate-version.outputs.semVer }}
      version: ${{ needs.calculate-version.outputs.semVer }}
    security: inherit