name: Publish Helm Umbrella Chart with Gradle and prepare for Environment Deployment
run-name: Integrate Service ${{ inputs.source-repo }} Helm Chart to Umbrella Helm Chart / Publish / Prepare Environment for Branch ${{ inputs.branch-name }} Version ${{ inputs.version-number }} with Chart Base Branch ${{ inputs.umbrella-chart-base-branch-name }} triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      branch-name:
        required: true
        type: string
      umbrella-chart-base-branch-name:
        required: true
        type: string
      source-repo:
        required: true
        type: string
      version-number:
        required: true
        type: string
jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Display Branch
        run: |
          echo "Branch: ${{ github.ref }}"
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-name }}
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
          additionalArguments: '"/b" "${{ inputs.branch-name }}"'
      - name: Display GitVersion ouput
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
  helm-publish-umbrella-chart:
    needs: calculate-version
    uses: ./.github/workflows/helm-publish-for-service.yaml
    with:
      source-repo: ${{ inputs.source-repo }}
      umbrella-chart-version: ${{ needs.calculate-version.outputs.semVer }}
      service-version-number: ${{ inputs.version-number }}
    secrets: inherit
  prepare-dev-environment:
    name: Building Dev Environment for Kubernetes
    needs:
      - helm-publish-umbrella-chart
      - calculate-version
    uses: ./.github/workflows/prepare-dev-environment.yaml
    with:
      branch-name: ${{ inputs.branch-name }}
      umbrella-chart-base-branch-name: ${{ inputs.umbrella-chart-base-branch-name }}
      tag: ${{ inputs.source-repo }}-${{ needs.calculate-version.outputs.semVer }}
      version: ${{ needs.calculate-version.outputs.semVer }}
    secrets: inherit
